#!/bin/sh

. ./_setup_environment

export LIBJARS=$JARS/json-simple-1.1.1.jar
export HADOOP_CLASSPATH=$(echo ${LIBJARS} | sed s/,/:/g)

ant jar
$RUN hdfs dfs -test -d $RESULTS && $RUN hdfs dfs -rm -r $RESULTS
$RUN yarn jar jar/facebook.jar json $TEXT_TARGET $RESULTS -libjars $LIBJARS

$RUN hdfs dfs -test -f $JSON_TARGET && $RUN hdfs dfs -rm $JSON_TARGET
$RUN hdfs dfs -mv $RESULTS/part-r-00000 $JSON_TARGET
$RUN hdfs dfs -cat $JSON_TARGET
