#!/bin/sh

. ./_setup_environment

export LIBJARS=$JARS/avro-1.7.4.jar,$JARS/avro-mapred-1.7.4-hadoop2.jar
export HADOOP_CLASSPATH=$(echo ${LIBJARS} | sed s/,/:/g)

ant jar
$RUN hdfs dfs -test -d $RESULTS && $RUN hdfs dfs -rm -r $RESULTS
$RUN yarn jar jar/facebook.jar csv $TEXT_TARGET $RESULTS -libjars $LIBJARS
$RUN hdfs dfs -test -f $CSVF_TARGET && $RUN hdfs dfs -rm $CSVF_TARGET
$RUN hdfs dfs -mv $RESULTS/part-r-00000 $CSVF_TARGET
