#!/bin/sh

HDFS_DIR=/user/$(whoami)
DATA_DIR=$HDFS_DIR/dataset
DATA_FILE=facebook_combined.txt
LOCAL_FILE=dataset/$DATA_FILE
REMOTE_FILE=$DATA_DIR/$DATA_FILE
RESULTS_DIR=report
RUN=../tools/exec

ant jar
$RUN hdfs dfs -test -d $HDFS_DIR || $RUN hdfs dfs -mkdir $HDFS_DIR || exit
$RUN hdfs dfs -test -d $DATA_DIR || $RUN hdfs dfs -mkdir $DATA_DIR || exit
$RUN hdfs dfs -test -f $REMOTE_FILE || $RUN hdfs dfs -put $LOCAL_FILE $REMOTE_FILE || exit
$RUN hdfs dfs -test -d $RESULTS_DIR && $RUN hdfs dfs -rm -r $RESULTS_DIR
$RUN yarn jar jar/*.jar $REMOTE_FILE $RESULTS_DIR
$RUN hdfs dfs -cat $RESULTS_DIR/*