#!/bin/sh

HDFS_DIR=/user/$(whoami)
DATA_DIR=$HDFS_DIR/dataset
DATA_FILE=payments.log
LOCAL_FILE=dataset/$DATA_FILE
REMOTE_FILE=$DATA_DIR/$DATA_FILE
RESULTS=report
RUN=../tools/exec

$RUN hdfs dfs -test -d $HDFS_DIR || $RUN hdfs dfs -mkdir $HDFS_DIR || exit
$RUN hdfs dfs -test -d $DATA_DIR || $RUN hdfs dfs -mkdir $DATA_DIR || exit
$RUN hdfs dfs -test -f $REMOTE_FILE || $RUN hdfs dfs -put $LOCAL_FILE $REMOTE_FILE || exit
$RUN hdfs dfs -test -d $RESULTS && $RUN hdfs dfs -rm -r $RESULTS
$RUN yarn jar jar/payments.jar $REMOTE_FILE $RESULTS
$RUN hdfs dfs -cat $RESULTS/*