#!/bin/bash

echo "Execution plan with Map/Reduce"
cat hql/mr.hql hql/3_subquery.hql | ssh hduser@vm0 "bash -ic hive -hivevar hive.execution.engine=mr" > plan_with_mr
echo "Execution plan with Apache Tez"
cat hql/tez.hql hql/3_subquery.hql | ssh hduser@vm0 "bash -ic hive -hivevar hive.execution.engine=tez" > plan_with_tez

diff plan_with_mr plan_with_tez

